services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aiapp_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: redis_broker
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_vector_db
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

  app:
    build: .
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - qdrant
    env_file:
      - .env

  worker:
    build: .
    container_name: celery_worker
    command: celery -A core.tasks worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - app
    env_file:
      - .env

volumes:
  postgres_data:
  qdrant_storage:
